### ISSUE TITLE
with lambda-packages installed, psycopg2 is still not actually available to zappa-based django deployment

### ISSUE THREAD

**Issue by scott2b** [Miserlou/lambda-packages#4]
As far as I can see from the docs, I should be able to use psycopg2 with django-zappa now that lambda-packages is installed. This does not seem to be the case.Tailing the logs reveals:

`module initialization error: Error loading psycopg2 module: No module named psycopg`

**Comment by Miserlou** [comment]
Thanks for reporting this. Can you give me a bit more information about your configuration? Ie, which version of lambda-packages, Zappa and django-zappa? It's possible something didn't make it into pip yet.

**Comment by scott2b** [comment]
Django==1.8.9
django-zappa==0.12.1
lambda-packages==0.3.0

It turns out psycopg2 was not in my local environment. I installed that a updated my lambda and the error is gone. It is unintuitive that Zappa seems to use the local environment rather than, say, a requirements.txt file for setting up the deployment. Perhaps there is a technical reason for that. Regardless, as far as I can tell I was just doing it wrong. The deployment is now not finding the urls.py file, but that is a different issue.

**Comment by Miserlou** [comment]
Ah, okay. Yeah, there is a technical reason for that, it's just the nature of lambda. How could we have explained this better for you?

Thanks for using Zappa!

**Comment by scott2b** [comment]
I would probably have a short section in the README file with the header "why is there no requirements.txt file" that states something like "Because of the way Lambda works, django-zappa uses your local environment to determine the deployed environment setup. Be sure to have all required dependencies installed in the virtualenvironment you are using for provisioning and update so that Zappa can know what dependencies to install on Lambda"

So, just something short that hits the keywords people will be looking for (requirements.txt, virtualenvirnoment, dependencies). I don't think you need to fully explain why in the README, just a short statement that this is the way it is.
