### ISSUE TITLE
Getting 'invalid ELF header' error on Lamba

### ISSUE THREAD

**Issue by sul4bh** [Miserlou/lambda-packages#58]
When I do a `zappa deploy dev` and call my API, I am getting this error:
`ImportError: /var/task/PIL/_imaging.so: invalid ELF header`

I am deploying from OSX. My guess is the precompiled binaries for OSX is being used by zappa on Lamba/Linux.

Did anyone run into something similar? How can it be fixed?

**Comment by sul4bh** [comment]
@Miserlou any idea what might be going on?

**Comment by bennettrogers** [comment]
I'm just starting to learn Zappa, but the "invalid ELF header" error is definitely a sign that your lambda is using a precompiled binary for a different architecture. 

See [this stackoverflow post](https://stackoverflow.com/questions/34881240/aws-unable-to-import-module-process-var-task-numpy-core-multiarray-so-in).

**Comment by sul4bh** [comment]
I was getting the error because PIL from my global packages somehow got uploaded to Lambda.
