### ISSUE TITLE
SQLite on Python 3 Lambda

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/lambda-packages#66]
Python3 lambdas don't have SQLite, even though it's part of the normal stdlib. We need to figure out how to package it in. May require another meta-package?

**Comment by Miserlou** [comment]
[_sqlite3.so.zip](https://github.com/Miserlou/lambda-packages/files/1425358/_sqlite3.so.zip)

@flipperpa made this on a CentOS box and says just dropping it into the root dir of a Py3 lambda project works. The problem is now we need to have some custom code in the Zappa packager to include it, because this is part of stdlib and not a site package.

**Comment by FlipperPA** [comment]
Just for reference, `_sqlite3.so` was taken from CentOS 7.2.1511 with Python 3.6.2. After deploy, I successfully migrated, created a superuser, and loaded fixtures: https://59l3oofv39.execute-api.us-east-1.amazonaws.com/production/ So it's been put through a few of the paces, at least.

**Comment by Miserlou** [comment]
This should be resolved in the latest Zappa.
