### ISSUE TITLE
PyYAML

### ISSUE THREAD

**Issue by gene1wood** [Miserlou/lambda-packages#68]
Would a package of PyYAML be welcome in this repo? Is it better to use a pure python implementation of YAML in lambda to avoid this issue and if so, what's recommended?

If not, I can submit a PR with an Amazon linux built (with build steps in README) PyYAML package.

**Comment by Miserlou** [comment]
Are you having troubles with PyYAML on Lambda? PyYAML is actually already a Zappa dependency, maybe it falls back to a pure python implementation under the hood? Or maybe the Lambda environment already contains `libyaml` just be random chance? Actually, it's possible that `PyYAML` itself falls back to a pure python version if `libyaml` isn't available? I'd have to dig in more, if you have more info.

**Comment by gene1wood** [comment]
> Are you having troubles with PyYAML on Lambda?

Since it uses a compiled shared object I've been building it in amazon linux then fetching and adding it to my lambda deployment packages

> PyYAML is actually already a Zappa dependency, maybe it falls back to a pure python implementation under the hood?

Ya, in this case I'm not using Zappa. So I guess the tangential question is, does it make sense to have lambda-packages in this repo that don't relate to Zappa/aren't part of the Zappa deployment framework?

> maybe it falls back to a pure python implementation under the hood?

It says that it now falls back to pure python if compilation fails. But in my case if I build my deployment package on my ubuntu system, then compilation succeeds and includes a shared object that wasn't built on Amazon Linux.

Anyhow, not urgent but I guess that's the real question "does it make sense to have lambda-packages in this repo that don't relate to Zappa/aren't part of the Zappa deployment framework?"

**Comment by Miserlou** [comment]
None of the packages here are Zappa specific, just common things for the convenience of all. The manifest file needs to be updated to be used by Zappa, but the packages themselves are all independent.

Does PyYAML break entirely if the _wrong_ object is there (rather than the missing object) - or does it just fall back to pure Python either way?

Either way, happy to accept a PR if it'll speed up YAML processing for Zappa users.

**Comment by gene1wood** [comment]
Actually, it looks like it works fine. If I install PyYAML to a directory to package up for use in Lambda, it installs without any dependency on libyaml. I'm unsure if this relates to the specific setup I have on my dev machine.

Anyhow, in my case doing a `pip install PyYAML --target path/to/builddir` and then zipping up the resulting content worked.

So let's ignore this for the time being.
