### ISSUE TITLE
Support for pycrypto

### ISSUE THREAD

**Issue by randuhmm** [Miserlou/lambda-packages#9]
Hello, I am interested in using pycrypto on AWS Lambda. If I am not mistaken, I can simply spin up a Amazon Linux EC2 instance and build the module and then upload for testing on Lambda, correct?. If so, I have no problem doing this myself and submitting a PR for the added package. Are there any caveats that I should be aware of? Thanks for your work on this and Django Zappa!

**Comment by Miserlou** [comment]
Yes, that should be fine.

Ideally, you'll also provide deterministic build instructions so that other people can reproduce the steps for creating the package if they want to do it themselves. With crypto code, you can see why.

**Comment by randuhmm** [comment]
Sorry, I just noticed that I goofed on the manifest naming. I should have named the dictionary key `pycrypto` rather than `Crypto`.

**Comment by Miserlou** [comment]
No, that's actually correct. It should match the lib/site-packages name, not the PyPI name.

**Comment by randuhmm** [comment]
This might warrant some more investigation because according to the Zappa build process it uses the output from `package.project_name` attribute to locate packages in the lambda_packages manifest that need to be replaced: https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L319-L333

The output from `pip show pycrypto` is:

    $ pip show pycrypto
    ---
    Name: pycrypto
    Version: 2.6.1
    Location: c:\path\to\site-packages
    Requires:

I think the `package.project_name` is the same value as the `Name: pycrypto` referenced above.

**Comment by Miserlou** [comment]
OH. Then you're right. Damn, son.

**Comment by randuhmm** [comment]
@Miserlou haha no worries man, nobody's perfect :P
